# Generated by Django 5.0.2 on 2024-03-02 19:33

import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=100, verbose_name="Имя пользователя"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=200,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Эл. почта",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
            ],
            options={
                "verbose_name": "Мои пользователи",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
