# Generated by Django 5.0.2 on 2024-03-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="otp",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
