# Generated by Django 5.0.2 on 2024-03-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verify",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_expiration",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Срок кода"),
        ),
    ]
