# Generated by Django 5.0.2 on 2024-03-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=255, verbose_name="Название группы"),
                ),
                (
                    "min_users",
                    models.PositiveIntegerField(
                        verbose_name="мин. количество участников"
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        verbose_name="макс. количество участников"
                    ),
                ),
            ],
            options={
                "verbose_name": "Группы",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group",
                        to="courses.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.customuser",
                        verbose_name="group_user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Название продукта"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Описание"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Дата начало")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Цена"
                    ),
                ),
                (
                    "lesson_count",
                    models.PositiveIntegerField(
                        null=True, verbose_name="Количество уроков"
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                ("is_buying", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to="users.customuser",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукты",
                "verbose_name_plural": "Продукт",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "link",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_lesson",
                        to="courses.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уроки",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_product",
                to="courses.product",
            ),
        ),
    ]
